name: cybersafe_pro
description: "A new Flutter project."
publish_to: "none"
version: 2.4.0+131

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #provider
  path: ^1.9.1
  tuple: ^2.0.2
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  #database
  csv: ^6.0.0

  # Drift database vá»›i SQLCipher
  drift: ^2.29.0
  sqlite3: ^2.9.4
  sqlcipher_flutter_libs: ^0.6.8

  #security
  crypto: ^3.0.7
  envied: ^1.3.1
  encrypt: ^5.0.3
  local_auth: ^3.0.0
  pointycastle: ^3.9.1
  url_launcher: ^6.3.2
  secure_application:
    git:
      url: https://github.com/dducnv/secure_application
      ref: master
  flutter_secure_storage: ^9.2.4
  local_auth_darwin: ^2.0.0
  #util
  intl: ^0.20.0
  logger: ^2.6.2
  croppy: ^1.4.1
  lottie: ^3.3.2
  shimmer: ^3.0.0
  timezone: ^0.10.0
  pie_chart: ^5.4.0
  share_plus: ^10.1.4
  flutter_svg: ^2.0.17
  file_picker: ^10.3.3
  # app_links: ^6.4.0
  diacritic: ^0.1.6
  characters: ^1.4.0
  image_picker: ^1.2.0
  numberpicker: ^2.1.2
  desktop_window: ^0.4.2
  in_app_review: ^2.0.11
  pin_code_fields: ^8.0.1
  downloadsfolder: ^1.2.0
  device_info_plus: ^12.2.0
  flutter_speed_dial: ^7.0.0
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  flutter_styled_toast: ^2.2.1
  flutter_native_splash: ^2.4.7
  qr_code_scanner_plus: ^2.0.14
  password_strength_checker: ^1.2.4
  flutter_staggered_animations: ^1.1.1
  flutter_quill: ^11.5.0
  flutter_colorpicker: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  envied_generator: ^1.3.1
  build_runner: ^2.10.1
  drift_dev: ^2.29.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/icons/brand_icons/
    - assets/icons/brand_icons/banks/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          style: italic
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
          weight: 100
          style: italic
